theme: jekyll-theme-architect

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
title: Think Machine 4E Advisor
description: Fading Suns character sheet generator UI based on Java for Fading Suns 4e.
author: 
  name: Jorge Hortelano
  email: softwaremagico@gmail.com

image:
  path: blob/master/images/think_machine_logo_fenix.png