plugins {
    alias(libs.plugins.android.application)
    id 'jacoco'
}

base {
    archivesName = "com.softwaremagico.tm-v10"
}

android {
    namespace 'com.softwaremagico.tm.advisor'
    compileSdk 37

    signingConfigs {
        File keystoreFileConfig = rootProject.file('../../Documentos/Android Keys/keystore.config')
        release {
            Properties keystoreProps = new Properties()
            if (keystoreFileConfig.exists()) {
                keystoreProps.load(new FileInputStream(keystoreFileConfig))

                keyAlias keystoreProps['keyAlias']
                keyPassword keystoreProps['keyPassword']
                storePassword keystoreProps['storePassword']
                storeFile file('../../../Documentos/Android Keys/AndroidKeyStore.jks')
            }
        }
        beta {
            Properties keystoreProps = new Properties()
            if (keystoreFileConfig.exists()) {
                keystoreProps.load(new FileInputStream(file(keystoreFileConfig)))

                keyAlias keystoreProps['keyAlias']
                keyPassword keystoreProps['keyPassword']
                storePassword keystoreProps['storePassword']
                storeFile file('../../../Documentos/Android Keys/AndroidKeyStore.jks')
            }
        }
        alpha {
            Properties keystoreProps = new Properties()
            if (keystoreFileConfig.exists()) {
                keystoreProps.load(new FileInputStream(file(keystoreFileConfig)))

                keyAlias keystoreProps['keyAlias']
                keyPassword keystoreProps['keyPassword']
                storePassword keystoreProps['storePassword']
                storeFile file('../../../Documentos/Android Keys/AndroidKeyStore.jks')
            }
        }
    }

    defaultConfig {
        applicationId "com.softwaremagico.tm"
        minSdk 31
        targetSdk 37
        versionCode 15
        versionName "0.6.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
        }

        beta {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            versionNameSuffix "-beta"
            signingConfig signingConfigs.beta
        }

        alpha {
            minifyEnabled false
            versionNameSuffix "-alpha"
            signingConfig signingConfigs.alpha
        }

        debug {
            minifyEnabled false
            versionNameSuffix "-debug"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }
    buildFeatures {
        buildConfig true
    }
}

jacoco {
    toolVersion = "0.8.11"
}

tasks.register('jacocoTestReport', JacocoReport) {
    dependsOn 'testDebugUnitTest'

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }

    def fileFilter = [
            '**/R.class',
            '**/R$*.class',
            '**/BuildConfig.*',
            '**/Manifest*.*',
            '**/*Test*.*',
            '**/*\$Lambda$*.*',
            '**/*Companion*.*',
            '**/*Factory*.*',
            '**/*Mapper*.*',
            '**/*Module*.*',
            '**/*_MembersInjector.class',
            '**/*_Factory.*',
            '**/*_Provide*Factory*.*',
            '**/*FragmentArgs*.*',
            '**/*FragmentDirections*.*',
            '**/*\$ViewInjector*.*'
    ]

    def debugTree = fileTree(dir: "$buildDir/intermediates/javac/debug/compileDebugJavaWithJavac/classes", excludes: fileFilter)
    def kotlinTree = fileTree(dir: "$buildDir/tmp/kotlin-classes/debug", excludes: fileFilter)

    classDirectories.setFrom(files([debugTree, kotlinTree]))
    sourceDirectories.setFrom(files(['src/main/java']))
    executionData.setFrom(fileTree(dir: buildDir, includes: [
            'jacoco/testDebugUnitTest.exec',
            'outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec'
    ]))
}

task checkstyle(type: Checkstyle) {
    description 'Check code standards'
    group 'verification'
    configFile file('checkstyle.xml')
    source 'src'
    include '**/*.java'
    exclude '**/gen/**'
    classpath = files()
    ignoreFailures = false
}

task pmd(type: Pmd) {
    ruleSetFiles = files("pmd-rules.xml")
    ignoreFailures = false
    ruleSets = []
    source 'src'
    include '**/*.java'
    exclude '**/gen/**'
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.think.machine.random
    testImplementation libs.junit
    testImplementation 'org.mockito:mockito-core:5.2.0'
    testImplementation 'org.mockito:mockito-inline:5.2.0'
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.fragment.testing
    debugImplementation libs.fragment.testing.manifest
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.think.machine.pdf
    implementation libs.cardview
    implementation libs.recyclerview
    implementation libs.room.runtime
    annotationProcessor libs.room.compiler
    implementation libs.core.splashscreen
    implementation libs.stax.api
    implementation libs.android.awt

    // Soporte desugering para APIs Java 15+
    coreLibraryDesugaring libs.desugar.jdk.libs
}